### PR TITLE
Add snapshot proposal info to 'node status'.

### PR DESCRIPTION
**Pull request by 0xfornax**
Showing information about active Snapshot proposals on `rocketpool node status`.

### CODE REVIEW

**Comment by 0xfornax** [comment]
This is how those changes look:
image

**Comment by 0xfornax** [comment]
After the latest changes:
image

**Comment by jclapis** [comment]
Hey Fornax, this is almost ready to go - I just request you take out the details of the votes from `node status` but leave the count; I think the details are best provided in their own command like `rocketpool network dao-proposals` or something. You're already 99% of the way there since you have a method in the daemon.

**Comment by 0xfornax** [comment]
@jclapis I have moved the voting details to `rocketpool network dao-proposals` please take a look.

**Comment by jclapis** [comment]
Outstanding, thank you for adding this!

**Pull request merged**
